//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bus.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class JourneyRoute
    {
        [DataMember]
        public int RouteID { get; set; }
        [DataMember]
        public int TripID { get; set; }
        [DataMember]
        public string CompanyName { get; set; }
        [DataMember]
        public string FromLocation { get; set; }
        [DataMember]
        public string ToLocation { get; set; }
        [DataMember]
        public System.DateTime FromDate { get; set; }
        [DataMember]
        public System.DateTime ToDate { get; set; }
        [DataMember]
        public System.TimeSpan FromTime { get; set; }
        [DataMember]
        public System.TimeSpan ToTime { get; set; }
        [DataMember]
        public string FromDescription { get; set; }
        [DataMember]
        public string ToDescription { get; set; }
        [DataMember]
        public int Fare { get; set; }
        [DataMember]
        public int NumberOfSeats { get; set; }
    
        public virtual Trip Trip { get; set; }
    }
}
